name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Maven
      run: mvn -B package --file pom.xml
      
    - name: Test
      run: mvn test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      #https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} #Here
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx b
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/simplecrud:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: SSH into server and deploy container
      uses: appleboy/ssh-action@v0.1.2 # https://github.com/appleboy/ssh-action
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          chmod +x deploy.sh
          ./deploy.sh




